networks:
  proxy-tier:
    external: true
  stack:
    external: false

services:
  www:
    image: ghcr.io/wonderkamer/website:${SEMVER_TAG}
    container_name: wonderkamer-development
    environment:
      VIRTUAL_HOST: "dev.wonderkamer.com"
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: "dev.wonderkamer.com"
      LETSENCRYPT_EMAIL: "hallo@wonderkamer.com"

      SEMVER_TAG: "${SEMVER_TAG}"
      GOOGLE_RECAPTCHA_SECRET: "${GOOGLE_RECAPTCHA_SECRET}"
      SERVER_PUBLIC_URL: "https://dev.wonderkamer.com"
      REDIS_HOST: "redis"
      SMTP_PASS: "${SMTP_PASS}"
      SMTP_USER: "${SMTP_USER}"
      SMTP_HOST: "${SMTP_HOST}"
      SMTP_PORT: "${SMTP_PORT}"
    networks:
      - proxy-tier
      - stack
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 150M

  redis:
    image: redis:7.2-alpine3.18
    # ports:
    #   - 6379:6379
    volumes:
      - redis:/data
    networks:
      - stack

volumes:
  redis:
    driver: local
