name: Development Deploy

on:
  workflow_dispatch:

  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8.*
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          pnpm install --frozen-lockfile --ignore-scripts

      - name: Install dependencies and build
        run: |
          pnpm run build-dev

      - name: Copy development htaccess
        uses: canastro/copy-file-action@master
        with:
          source: 'public/htaccess-development.txt'
          target: 'dist/.htaccess'

      - name: Install dotenv file
        run: |
          echo "GOOGLE_RECAPTCHA_SECRET=\"${{ secrets.GOOGLE_RECAPTCHA_SECRET }}\"" > dist/.env
          echo "SMTP_PASSWORD=\"${{ secrets.SMTP_PASSWORD }}\"" >> dist/.env
          echo "CONTACT_FORM_RECIPIENT=\"hallo@wonderkamer.com\"" >> dist/.env

      - name: Install PHP dependencies (into /dist/vendor)
        uses: mileschou/composer-action/8.0/install@master
        with:
          args: 'install --working-dir=./dist --prefer-dist --no-interaction --no-progress'

      - name: Archive distribution directory
        run: tar -cvf build.tar dist

      - name: Persist distribution directory (/dist as 'build-dev')
        uses: actions/upload-artifact@v3.1.2
        with:
          name: build-dev-${{ github.head_ref || github.ref }}
          path: build.tar
          retention-days: 1

  deploy-to-develop:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Retrieve distribution
        uses: actions/download-artifact@v3.0.2
        with:
          name: build-dev-${{ github.head_ref || github.ref }}
          path: dist

      - name: Extract distribution
        run: tar -xvf build.tar

      - name: Deploy
        uses: contention/rsync-deployments@v2.0.0
        with:
          flags: -avzr --delete-after
          excludes:
          user: wonderkamercom
          host: wondey.ssh.transip.me
          localpath: /dist/
          remotepath: /data/sites/web/wonderkamercom/subdomains/dev
          deploy_key: ${{ secrets.DEPLOY_KEY }}
