name: Development Deploy

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install dependencies and build
      run: |
        yarn install
        yarn build
        sed -i 's/\$GOOGLE_RECAPTCHA_SECRET/${{ secrets.GOOGLE_RECAPTCHA_SECRET }}/g' dist/.htaccess

    - name: Install PHP dependencies (into /dist/vendor)
      uses: nick-zh/composer-php@php7.4
      with:
        action: 'install --working-dir=./dist --no-suggest --prefer-dist --no-interaction --no-progress'

    - name: Persist distribution directory (/dist as 'build-dev')
      uses: actions/upload-artifact@v2
      with:
        name: build-dev
        path: dist/

  deploy-to-githubio:
    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Retrieve distribution
      uses: actions/download-artifact@v2
      with:
        name: build-dev
        path: dist

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: Wunderkammer-Amsterdam/wunderkammer-amsterdam.github.io
        BRANCH: master # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.


  # see https://github.com/SamKirkland/FTP-Deploy-Action
  deploy-to-dev:
    runs-on: ubuntu-latest

    needs: build

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Retrieve distribution
      uses: actions/download-artifact@v2
      with:
        name: build-dev
        path: dist

    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        local-dir: dist/
        ftp-server: sftp://sftp.greenconcepts.nl/public/sites/dev.wunderkammeramsterdam.nl
        ftp-username: ${{ secrets.SFTP_USERNAME }}
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        git-ftp-args: --insecure
