on:
  workflow_dispatch:
  schedule:
    - cron: "11 3 */7 * *"

name: "Purge Packages"

jobs:
  purge-packages:
    name: "Purge Packages"

    permissions:
      packages: write

    runs-on: "ubuntu-latest"

    steps:
      - name: "Purge"
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          owner: wonderkamer
          repository: website
          dry-run: false
          keep-n-tagged: 15
          delete-untagged: true
          delete-partial-images: true
          delete-orphaned-images: true
          validate: true
          log-level: "debug"
          packages: "website"
